// src/pages/tags/[id].tsx
import Head from "next/head";
import { useState } from "react";
import { WordList } from "@/components/WordList";
import { I18n, validateLocale } from "@/libs/i18n";
import { validateTag } from "@/libs/tags";
import allTags from "../../../public/dataset/tags.json";
import type { GetServerSideProps, InferGetServerSidePropsType } from "next";
import type { Locale, TagID } from "@/types";

type Props = {
  locale: Locale,
  tagID: TagID,
};

export const getServerSideProps: GetServerSideProps<Props> = async ({ locale, params }) => {
  try {
    const tagID: TagID = validateTag(params?.id as string);

    return {
      props: {
        locale: validateLocale(locale),
        tagID,
      },
    };
  } catch (err) {
    if (err instanceof TypeError && err.message === "UNEXPECTED_TAG") {
      return {
        notFound: true,
      };
    } else {
      throw err;
    }
  }
};

export default function TagIDPage({ locale, tagID }: InferGetServerSidePropsType<typeof getServerSideProps>): JSX.Element {
  const i18n = new I18n(locale, {
    en: {},
    ja: {},
    "zh-CN": {},
  });

  const [ title, setTitle ] = useState(`${allTags[tagID].title[locale]} | ${i18n.t("siteTitle")}`);

  //
  // Event Handlers
  //
  const onSearch = (): void => {
    const root = `/${locale}/`;

    if (window.location.pathname !== root) {
      history.pushState({}, "", root);
      setTitle(i18n.t("siteTitle"));
    }
  };

  return (
    <>
      <Head>
        <title>{ title }</title>
        <meta property="og:title" content={ title } />
        {/* TODO
          <meta name="description" content={ description } />
          <meta property="og:description" content={ description } />
        */}
      </Head>
      <WordList locale={locale} tagID={tagID} onSearch={onSearch} />
    </>
  );
}

// pages/tags/[id].vue
<template>
  <word-list @search="onSearch" />
</template>

<script lang="ts" setup>
import { useDictionaryStore } from "~/store/index";
import tags from "~/dataset/tags.json";
import type { Locale } from "~/types";

const { $pinia } = useNuxtApp();
const { locale, t } = useI18n<[], Locale>({
  useScope: "local",
});
const route = useRoute();
const store = useDictionaryStore($pinia);

const tagID = route.params.id;

const title = ref(`${tags[tagID].title[locale.value]} | ${t("siteTitle")}`);

useHead({
  title,
  meta: [
    { hid: "og:title", property: "og:title", content: title.value },
  ],
});

useLazyAsyncData("initTag", async () => {
  store.$reset();
  store.addTags(tagID);
});

onMounted(() => {
  // Reset on browser back
  window.onpopstate = () => {
    store.$reset();
    store.addTags(tagID);
  };
});

const onSearch = (): void => {
  const root = `/${locale.value}`;

  if (window.location.pathname !== root) {
    history.pushState({}, "", root);
    title.value = t("siteTitle");
  }
};
</script>
